apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deployment-session-db-sock-shop
  namespace: sock-shop
spec:
  egress: []
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: sock-shop
      podSelector:
        matchLabels:
          name: front-end
    ports:
    - port: 6379
  podSelector:
    matchLabels:
      name: session-db
  policyTypes:
  - Ingress
  - Egress
