apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deployment-catalogue-sock-shop
  namespace: sock-shop
spec:
  egress:
  - ports:
    - port: 3306
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: sock-shop
      podSelector:
        matchLabels:
          name: catalogue-db
  ingress: []
  podSelector:
    matchLabels:
      name: catalogue
  policyTypes:
  - Ingress
  - Egress
